// <auto-generated />
namespace FilmPhotoJournalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class photocollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(photocollection));
        
        string IMigrationMetadata.Id
        {
            get { return "202306142007061_photo-collection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
